build: 
	sass binary/medium/styles.scss binary/medium/styles.css
	sass binary/light/styles.scss binary/light/styles.css
	sass binary/dark/styles.scss binary/dark/styles.css

	sass non-binary/medium/styles.scss non-binary/medium/styles.css
	sass non-binary/light/styles.scss non-binary/light/styles.css
	sass non-binary/dark/styles.scss non-binary/dark/styles.css

	sass monochrome/medium/styles.scss monochrome/medium/styles.css
	sass monochrome/light/styles.scss monochrome/light/styles.css
	sass monochrome/dark/styles.scss monochrome/dark/styles.css

	sass shaded/styles.scss shaded/styles.css
	sass colored/styles.scss colored/styles.css
	sass colorful/styles.scss colorful/styles.css
	sass accented/styles.scss accented/styles.css